version: '3.1'

services:
  db:
    image: mysql:latest
    container_name: mock-shirt-dev
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - ./mysql-volume:/var/lib/mysql
  app:
    image: mock-shirt-api
    container_name: mock-shirt-api 
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    networks:
      - my_network
    depends_on:
      - db

networks:
  my_network:
    driver: bridge